name: Check Pull Request

on:
  pull_request:
    branches:
      - main
    paths:
      - cronpar/**
      - tests/**
      - pyproject.toml
      - poetry.lock

jobs:
  pr-check:
    name: test cronpar
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        python-version: [ "3.8.12", "3.9", "3.10.6", "3.11" ]
    steps:
      - name: checkout
        uses: actions/checkout@v2.4.0
        with:
          fetch-depth: 0
      - name: Install Python
        uses: actions/setup-python@v2.3.0
        with:
          python-version: 3.10.6
      - name: Install Poetry
        run: |
          python -m pip install --upgrade pip
          python -m pip install "poetry<1.3"
          poetry config virtualenvs.create false
        shell: bash
      - name: Install Python dependencies
        run: poetry install
        shell: bash
      - name: Lint
        working-directory: ${{ inputs.working-directory }}
        run: make lint
        shell: bash
      - name: Run test
        working-directory: ${{ inputs.working-directory }}
        run: make test
        shell: bash
