name: Build and Publish cronpar

on:
  release:
    types:
      - published

jobs:
  publish:
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.9]
        poetry-version: [1.2.1]
        poetry-core-version: [1.2.0]
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: Publish PyPi package
        uses: code-specialist/pypi-poetry-publish@v1
        with:
          ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PUBLISH_REGISTRY_PASSWORD: ${{ secrets.PYPI_TOKEN }}
          PYTHON_VERSION: ${{ matrix.python-version }}
          POETRY_VERSION: ${{ matrix.poetry-version }}
          POETRY_CORE_VERSION: ${{ matrix.poetry-core-version }}
          BRANCH: main
